export const translations = {
    uz: {
        new_project: "Yangi loyihani",
        todo_title: "Vazifalar",
        add_project: "Loyiha qo'shish",
        add_task: "Vazifa qo'shish",
        list_view: "Ro'yxat",
        board_view: "Board",
        search_tasks: "Vazifa qidirish...",
        filter_all: "Barchasi",
        filter_todo: "Bajarilmagan",
        filter_progress: "Jarayonda",
        filter_done: "Bajarilgan",
        no_tasks: "Vazifalar yo'q",
        no_projects: "Loyihalar yo'q. Birinchi loyihani yarating!",
        no_projects_title: "Loyiha yo'q",
        no_projects_desc: "Vazifa qo'shishdan oldin kamida bitta loyiha yarating.",
        status_todo: "Bajarilmagan",
        status_progress: "Jarayonda",
        status_done: "Bajarilgan",
        priority_none: "Prioritet yo'q",
        priority_low: "Past",
        priority_medium: "O'rta",
        priority_high: "Yuqori",
        priority_urgent: "Shoshilinch",
        assignee: "Ijrochi",
        due_date: "Muddat",
        priority: "Prioritet",
        actions: "Amallar",
        task_name_col: "Vazifa nomi",
        edit: "Tahrirlash",
        delete: "O'chirish",
        cancel: "Bekor qilish",
        save: "Saqlash",
        create: "Yaratish",
        modal_create_task: "Yangi vazifa yaratish",
        modal_edit_task: "Vazifani tahrirlash",
        modal_create_project: "Yangi loyiha yaratish",
        task_title_placeholder: "Vazifa nomini kiriting...",
        task_desc_placeholder: "Tavsif (ixtiyoriy)...",
        project_name_placeholder: "Loyiha nomini kiriting...",
        select_assignee: "Ijrochi tanlang",
        select_status: "Status tanlang",
        select_priority: "Prioritet tanlang",
        confirm_delete_task: "Bu vazifani o'chirmoqchimisiz?",
        confirm_delete_project: "Bu loyihani barcha vazifalari bilan o'chirmoqchimisiz?",
        col_todo: "BAJARILMAGAN",
        col_progress: "JARAYONDA",
        col_done: "BAJARILGAN",
        tasks_count: "ta vazifa",
        add_group: "+ Guruh qo'shish",
        empty_column: "Bu yerga vazifalar tashlang",
        project_label: "Loyiha nomi",
        task_label: "Vazifa nomi",
        description_label: "Tavsif",
        status_label: "Status",
        assignee_label: "Ijrochi",
        duedate_label: "Muddat",
        priority_label: "Prioritet",
        overdue: "Muddati o'tgan",
        today: "Bugun",
        no_users_yet: "Foydalanuvchilar yo'q",
        create_time: "Yaratilgan vaqt",
        task_created: "Vazifa muvaffaqiyatli yaratildi",
        task_updated: "Vazifa yangilandi",
        task_deleted: "Vazifa o'chirildi",
        status_updated: "Status yangilandi",
        project_created: "Loyiha yaratildi",
        project_updated: "Loyiha muvaffaqiyatli saqlandi",
        project_deleted: "Loyiha o'chirildi",
        error_saving_task: "Vazifani saqlashda xatolik",
        error_deleting_task: "Vazifani o'chirishda xatolik",
        error_updating_task: "Vazifani yangilashda xatolik",
        error_updating_status: "Statusni yangilashda xatolik",
        error_creating_project: "Loyihani yaratishda xatolik",
        error_saving_project: "Loyihani saqlashda xatolik",
        error_deleting_project: "Loyihani o'chirishda xatolik",
        error_occurred: "Xatolik yuz berdi",
        error_min_length_3: "Kamida 3 ta belgi bo'lishi kerak",
        error_max_length_20: "Maksimal 20 ta belgi bo'lishi kerak",
        error_no_permission: "Sizda bunday amalni bajarish uchun ruxsat yo'q",
        no_members_added: "Hali hech kim qo'shilmagan",
        project_settings: "Loyiha sozlamalari",
        project_overview: "Sozlamalar",
        search_by_username: "Username orqali qidirish...",
        search_by_email: "Email orqali qidirish...",
        search_users_placeholder: "Username yoki email orqali qidirish...",
        added_members: "Loyihaga qo'shilganlar",
        manage_access: "Kirish huquqlarini boshqarish",
        role_admin: "Admin",
        role_member: "Ishtirokchi",
        role_viewer: "Kuzatuvchi",
        public_project: "Ochiq loyiha (Public)",
        public_project_desc: "Loyiha barcha foydalanuvchilarga ko'rinadi (faqat ko'rish uchun)",
        add_member: "A'zo qo'shish",
        member_added: "A'zo muvaffaqiyatli qo'shildi",
        add: "Qo'shish",
        added_label: "Qo'shilgan",
        show: "Ko'rsatish",
        showing_label: "Ko'rsatilyapti",
        of_label: "tadan",
        show_label: "Ko'rsatish",
        prev: "Oldingi",
        next: "Keyingi",
        projects: "Loyihalar",
        search_projects: "Loyiha qidirish...",
        no_projects_found: "Loyihalar topilmadi",
        start_date_label: "Boshlanish sanasi",
        estimated_time_label: "Reja (soat)",
        actual_time_label: "Haqiqat (soat)",
        log_time: "Vaqtni kiritish",
        total_spent: "Jami sarflangan",
        time_by_users: "Xodimlar sarflagan vaqt",
        hours: "soat",
        history: "Tarix",
        project_history: "Loyiha tarixi",
        statistika: "Statistika",
        no_history_yet: "Tarixiy amallar hozircha mavjud emas",
        action_created: "yaratildi",
        action_updated: "tahrirlandi",
        action_deleted: "o'chirildi",
        action_status_changed: "statusi o'zgartirildi",
        total_tasks: "Jami vazifalar",
        top_assignees: "Ijrochilar",
        tasks_lbl: "vazifa",
        priority_dist: "Prioritet taqsimoti",
        tasks_done_lbl: "vazifa bajarilgan",
        attach_file_pdf: "PDF Fayl biriktirish (max 5MB)",
        attached_files: "Fayllar (PDF)",
        choose_file: "Fayl tanlash",
        no_file_chosen: "Fayl tanlanmagan",
        chat: "Chat",
        write_msg: "Xabar yozing...",
        send: "Yuborish",
        no_msgs_yet: "Hozircha xabarlar yo'q",
        chat_title: "Vazifa Chati",
        filter_btn: "Filtrlash",
        filter_title: "Vazifalar filtri",
        filter_reset: "Tozalash",
        filter_status: "Holat",
        filter_assignee: "Ijrochi",
        filter_my_tasks: "Menga biriktirilgan vazifalar",
        filter_priority: "Muhimlik",
        filter_deadline: "Muddati",
        filter_sort_deadline: "Tugashiga yaqinlari bo'yicha saralash",
        filter_date_range: "Muddat oralig'i",
        filter_date_from: "dan",
        filter_date_to: "gacha"
    },
    en: {
        new_project: "New Project",
        todo_title: "Tasks",
        add_project: "Add Project",
        add_task: "Add Task",
        list_view: "List",
        board_view: "Board",
        search_tasks: "Search tasks...",
        filter_all: "All",
        filter_todo: "To Do",
        filter_progress: "In Progress",
        filter_done: "Done",
        no_tasks: "No tasks yet",
        no_projects: "No projects. Create the first one!",
        no_projects_title: "No Project",
        no_projects_desc: "Please create at least one project before adding tasks.",
        status_todo: "To Do",
        status_progress: "In Progress",
        status_done: "Done",
        priority_none: "No priority",
        priority_low: "Low",
        priority_medium: "Medium",
        priority_high: "High",
        priority_urgent: "Urgent",
        assignee: "Assignee",
        due_date: "Due Date",
        priority: "Priority",
        actions: "Actions",
        task_name_col: "Task Name",
        edit: "Edit",
        delete: "Delete",
        cancel: "Cancel",
        save: "Save",
        create: "Create",
        modal_create_task: "Create New Task",
        modal_edit_task: "Edit Task",
        modal_create_project: "Create New Project",
        task_title_placeholder: "Enter task title...",
        task_desc_placeholder: "Description (optional)...",
        project_name_placeholder: "Enter project name...",
        select_assignee: "Select assignee",
        select_status: "Select status",
        select_priority: "Select priority",
        confirm_delete_task: "Delete this task?",
        confirm_delete_project: "Delete this project with all its tasks?",
        col_todo: "TO DO",
        col_progress: "IN PROGRESS",
        col_done: "DONE",
        tasks_count: "tasks",
        add_group: "+ Add Group",
        empty_column: "Drop tasks here",
        project_label: "Project Name",
        task_label: "Task Name",
        description_label: "Description",
        status_label: "Status",
        assignee_label: "Assignee",
        duedate_label: "Due Date",
        priority_label: "Priority",
        overdue: "Overdue",
        today: "Today",
        no_users_yet: "No users yet",
        create_time: "Created at",
        task_created: "Task created successfully",
        task_updated: "Task updated",
        task_deleted: "Task deleted",
        status_updated: "Status updated",
        project_created: "Project created",
        project_updated: "Project updated successfully",
        project_deleted: "Project deleted",
        error_saving_task: "Error saving task",
        error_deleting_task: "Error deleting task",
        error_updating_task: "Error updating task",
        error_updating_status: "Error updating status",
        error_creating_project: "Error creating project",
        error_saving_project: "Error saving project",
        error_deleting_project: "Error deleting project",
        error_occurred: "An error occurred",
        error_min_length_3: "Must be at least 3 characters",
        error_max_length_20: "Maximum 20 characters allowed",
        error_no_permission: "You don't have permission to perform this action",
        no_members_added: "No members added yet",
        project_settings: "Project Settings",
        project_overview: "Settings",
        search_by_username: "Search by username...",
        search_by_email: "Search by email...",
        search_users_placeholder: "Search by username or email...",
        added_members: "Project Members",
        manage_access: "Manage Access",
        role_admin: "Admin",
        role_member: "Member",
        role_viewer: "Viewer",
        public_project: "Public Project",
        public_project_desc: "Project is visible to all users (read-only)",
        add_member: "Add Member",
        member_added: "Member added successfully",
        add: "Add",
        added_label: "Added",
        show: "Show",
        showing_label: "Showing",
        of_label: "of",
        show_label: "Show",
        prev: "Prev",
        next: "Next",
        projects: "Projects",
        search_projects: "Search projects...",
        no_projects_found: "No projects found",
        start_date_label: "Start Date",
        estimated_time_label: "Plan (hours)",
        actual_time_label: "Actual (hours)",
        log_time: "Log Time",
        total_spent: "Total Spent",
        time_by_users: "Time by Users",
        hours: "hours",
        history: "History",
        project_history: "Project History",
        statistika: "Statistics",
        no_history_yet: "No activity history yet",
        action_created: "created",
        action_updated: "updated",
        action_deleted: "deleted",
        action_status_changed: "status changed",
        total_tasks: "Total Tasks",
        top_assignees: "Assignees",
        tasks_lbl: "tasks",
        priority_dist: "By Priority",
        tasks_done_lbl: "tasks completed",
        attach_file_pdf: "Attach PDF File (max 5MB)",
        attached_files: "Files (PDF)",
        choose_file: "Choose file",
        no_file_chosen: "No file chosen",
        chat: "Chat",
        write_msg: "Type a message...",
        send: "Send",
        no_msgs_yet: "No messages yet",
        chat_title: "Task Chat",
        filter_btn: "Filter",
        filter_title: "Task Filters",
        filter_reset: "Reset",
        filter_status: "Status",
        filter_assignee: "Assignee",
        filter_my_tasks: "Assigned to me",
        filter_priority: "Priority",
        filter_deadline: "Deadline",
        filter_sort_deadline: "Sort by closest deadline",
        filter_date_range: "Date Range",
        filter_date_from: "from",
        filter_date_to: "to"
    },
    ru: {
        new_project: "Новый проект",
        todo_title: "Задачи",
        add_project: "Добавить проект",
        add_task: "Добавить задачу",
        list_view: "Список",
        board_view: "Доска",
        search_tasks: "Поиск задач...",
        filter_all: "Все",
        filter_todo: "К выполнению",
        filter_progress: "В процессе",
        filter_done: "Выполнено",
        no_tasks: "Задач нет",
        no_projects: "Нет проектов. Создайте первый!",
        no_projects_title: "Нет проекта",
        no_projects_desc: "Создайте хотя бы один проект, прежде чем добавлять задачи.",
        status_todo: "К выполнению",
        status_progress: "В процессе",
        status_done: "Выполнено",
        priority_none: "Без приоритета",
        priority_low: "Низкий",
        priority_medium: "Средний",
        priority_high: "Высокий",
        priority_urgent: "Срочно",
        assignee: "Исполнитель",
        due_date: "Срок",
        priority: "Приоритет",
        actions: "Действия",
        task_name_col: "Название задачи",
        edit: "Редактировать",
        delete: "Удалить",
        cancel: "Отмена",
        save: "Сохранить",
        create: "Создать",
        modal_create_task: "Создать задачу",
        modal_edit_task: "Редактировать задачу",
        modal_create_project: "Создать проект",
        task_title_placeholder: "Введите название задачи...",
        task_desc_placeholder: "Описание (необязательно)...",
        project_name_placeholder: "Введите название проекта...",
        select_assignee: "Выберите исполнителя",
        select_status: "Выберите статус",
        select_priority: "Выберите приоритет",
        confirm_delete_task: "Удалить эту задачу?",
        confirm_delete_project: "Удалить этот проект со всеми задачами?",
        col_todo: "К ВЫПОЛНЕНИЮ",
        col_progress: "В ПРОЦЕССЕ",
        col_done: "ВЫПОЛНЕНО",
        tasks_count: "задач",
        add_group: "+ Добавить группу",
        empty_column: "Перетащите задачи сюда",
        project_label: "Название проекта",
        task_label: "Название задачи",
        description_label: "Описание",
        status_label: "Статус",
        assignee_label: "Исполнитель",
        duedate_label: "Срок",
        priority_label: "Приоритет",
        overdue: "Просрочено",
        today: "Сегодня",
        no_users_yet: "Пользователей нет",
        create_time: "Дата создания",
        task_created: "Задача успешно создана",
        task_updated: "Задача обновлена",
        task_deleted: "Задача удалена",
        status_updated: "Статус обновлен",
        project_created: "Проект создан",
        project_updated: "Проект успешно обновлен",
        project_deleted: "Проект удален",
        error_saving_task: "Ошибка при сохранении задачи",
        error_deleting_task: "Ошибка при удалении задачи",
        error_updating_task: "Ошибка при обновлении задачи",
        error_updating_status: "Ошибка при обновлении статуса",
        error_creating_project: "Ошибка при создании проекта",
        error_saving_project: "Ошибка при сохранении проекта",
        error_deleting_project: "Ошибка при удалении проекта",
        error_occurred: "Произошла ошибка",
        error_min_length_3: "Должно быть не менее 3 символов",
        error_max_length_20: "Максимум 20 символов",
        error_no_permission: "У вас нет прав для выполнения этого действия",
        no_members_added: "Участники пока не добавлены",
        project_settings: "Настройки проекта",
        project_overview: "Настройки",
        search_by_username: "Поиск по имени пользователя...",
        search_by_email: "Поиск по email...",
        search_users_placeholder: "Поиск по имени или email...",
        added_members: "Участники проекта",
        manage_access: "Управление доступом",
        role_admin: "Админ",
        role_member: "Участник",
        role_viewer: "Зритель",
        public_project: "Публичный проект",
        public_project_desc: "Проект виден всем пользователям (только чтение)",
        add_member: "Добавить участника",
        member_added: "Участник успешно добавлен",
        add: "Добавить",
        added_label: "Добавлен",
        show: "Показать",
        showing_label: "Показано",
        of_label: "из",
        show_label: "Показать",
        prev: "Пред",
        next: "След",
        projects: "Проекты",
        search_projects: "Поиск проектов...",
        no_projects_found: "Проекты не найдены",
        start_date_label: "Дата начала",
        estimated_time_label: "План (часов)",
        actual_time_label: "Факт (часов)",
        log_time: "Добавить время",
        total_spent: "Всего затрачено",
        time_by_users: "Время по пользователям",
        hours: "часов",
        history: "История",
        project_history: "История проекта",
        statistika: "Статистика",
        no_history_yet: "История пока пуста",
        action_created: "создана",
        action_updated: "изменена",
        action_deleted: "удалена",
        action_status_changed: "статус изменен",
        total_tasks: "Всего задач",
        top_assignees: "Исполнители",
        tasks_lbl: "задач",
        priority_dist: "По приоритетам",
        tasks_done_lbl: "задач выполнено",
        attach_file_pdf: "Прикрепить PDF файл (макс 5MB)",
        attached_files: "Файлы (PDF)",
        choose_file: "Выберите файл",
        no_file_chosen: "Файл не выбран",
        chat: "Чат",
        write_msg: "Напишите сообщение...",
        send: "Отправить",
        no_msgs_yet: "Пока нет сообщений",
        chat_title: "Чат задачи",
        filter_btn: "Фильтр",
        filter_title: "Фильтры задач",
        filter_reset: "Сбросить",
        filter_status: "Статус",
        filter_assignee: "Исполнитель",
        filter_my_tasks: "Назначенные мне",
        filter_priority: "Приоритет",
        filter_deadline: "Срок",
        filter_sort_deadline: "Сортировать по ближайшим срокам",
        filter_date_range: "Диапазон дат",
        filter_date_from: "от",
        filter_date_to: "до"
    },
};

export const TASK_TR = {
    uz: {
        btn: "Tahlil",
        title: "Vazifalar Tahlili",
        sub: "Barcha loyihalar bo'yicha",
        total_tasks: "Jami vazifalar",
        total_done: "Bajarilgan",
        in_progress: "Jarayonda",
        total_projects: "Loyihalar",
        status_dist: "Status taqsimoti",
        priority_dist: "Prioritet taqsimoti",
        top_assignees: "Ijrochilar",
        projects_prog: "Loyihalar bajarilishi",
        overdue: "Muddati o'tgan",
        done_rate: "Bajarilgan %",
        today_tasks: "Bugungi vazifalar",
        new_this_week: "Yangi (hafta)",
        no_data: "Ma'lumot yo'q",
        todo_lbl: "Bajarilmagan",
        prog_lbl: "Jarayonda",
        done_lbl: "Bajarilgan",
        tasks_lbl: "vazifa",
        footer: "Barcha loyihalar hisobga olindi",
        pri_none: "Prioritet yo'q",
        pri_low: "Past",
        pri_medium: "O'rta",
        pri_high: "Yuqori",
        pri_urgent: "Shoshilinch",
        assignee_tasks: "vazifa",
        overdue_lbl: "Muddati o'tgan",
        project_lbl: "loyiha",
    },
    ru: {
        btn: "Аналитика",
        title: "Аналитика задач",
        sub: "По всем проектам",
        total_tasks: "Всего задач",
        total_done: "Выполнено",
        in_progress: "В процессе",
        total_projects: "Проектов",
        status_dist: "Распределение статусов",
        priority_dist: "По приоритетам",
        top_assignees: "Исполнители",
        projects_prog: "Прогресс проектов",
        overdue: "Просроченные",
        done_rate: "% выполнено",
        today_tasks: "Задачи на сегодня",
        new_this_week: "Новые (неделя)",
        no_data: "Нет данных",
        todo_lbl: "К выполнению",
        prog_lbl: "В процессе",
        done_lbl: "Выполнено",
        tasks_lbl: "задач",
        footer: "Учтены все проекты",
        pri_none: "Без приоритета",
        pri_low: "Низкий",
        pri_medium: "Средний",
        pri_high: "Высокий",
        pri_urgent: "Срочно",
        assignee_tasks: "задач",
        overdue_lbl: "Просрочено",
        project_lbl: "проект",
    },
    en: {
        btn: "Analytics",
        title: "Tasks Analytics",
        sub: "Across all projects",
        total_tasks: "Total Tasks",
        total_done: "Completed",
        in_progress: "In Progress",
        total_projects: "Projects",
        status_dist: "Status Distribution",
        priority_dist: "By Priority",
        top_assignees: "Assignees",
        projects_prog: "Project Progress",
        overdue: "Overdue Tasks",
        done_rate: "Completion Rate",
        today_tasks: "Due Today",
        new_this_week: "New (week)",
        no_data: "No data yet",
        todo_lbl: "To Do",
        prog_lbl: "In Progress",
        done_lbl: "Done",
        tasks_lbl: "tasks",
        footer: "All projects are included",
        pri_none: "No priority",
        pri_low: "Low",
        pri_medium: "Medium",
        pri_high: "High",
        pri_urgent: "Urgent",
        assignee_tasks: "tasks",
        overdue_lbl: "Overdue",
        project_lbl: "project",
    },
};
